#!/bin/sh

gcc -I ../lua5.1/include/ -O2 -fno-common -c *.c
gcc -framework Carbon -framework ApplicationServices -bundle -Wl,-bind_at_load -undefined dynamic_lookup -o ../LightroomTether.lrplugin/LightroomUtils-OSX.so *.o
